//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrkIdea.QC.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.CustomerParameter = new HashSet<CustomerParameter>();
            this.DocumentType = new HashSet<DocumentType>();
            this.Page = new HashSet<Page>();
            this.Role = new HashSet<Role>();
            this.SideBar = new HashSet<SideBar>();
            this.UserProfile = new HashSet<UserProfile>();
            this.WorkFlow = new HashSet<WorkFlow>();
            this.Process = new HashSet<Process>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public bool activo { get; set; }
    
        public virtual ICollection<CustomerParameter> CustomerParameter { get; set; }
        public virtual ICollection<DocumentType> DocumentType { get; set; }
        public virtual ICollection<Page> Page { get; set; }
        public virtual ICollection<Role> Role { get; set; }
        public virtual ICollection<SideBar> SideBar { get; set; }
        public virtual ICollection<UserProfile> UserProfile { get; set; }
        public virtual ICollection<WorkFlow> WorkFlow { get; set; }
        public virtual ICollection<Process> Process { get; set; }
    }
}
