//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrkIdea.QC.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public Document()
        {
            this.DocumentVersion = new HashSet<DocumentVersion>();
        }
    
        public int id { get; set; }
        public Nullable<int> idProceso { get; set; }
        public int idTipoDocumento { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public bool activo { get; set; }
    
        public virtual DocumentType DocumentType { get; set; }
        public virtual ICollection<DocumentVersion> DocumentVersion { get; set; }
        public virtual Process Process { get; set; }
    }
}
