//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrkIdea.QC.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentVersion
    {
        public string id { get; set; }
        public int idDocumento { get; set; }
        public decimal version { get; set; }
        public System.DateTime fechaVersion { get; set; }
        public bool versionOficial { get; set; }
        public int idUsuario { get; set; }
        public string comentarios { get; set; }
    
        public virtual Document Document { get; set; }
    }
}
