//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrkIdea.QC.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page
    {
        public string id { get; set; }
        public int idCliente { get; set; }
        public string titulo { get; set; }
        public string contenido { get; set; }
        public string imagenPrincipal { get; set; }
        public Nullable<int> idCarrusel { get; set; }
        public Nullable<int> idSideBarDerecho { get; set; }
        public Nullable<int> idSideBarIzquierdo { get; set; }
        public bool privado { get; set; }
        public bool visible { get; set; }
        public string metaData { get; set; }
        public string keyWord { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
