//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrkIdea.QC.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public int id { get; set; }
        public int idCliente { get; set; }
        public int idRol { get; set; }
        public string usuario { get; set; }
        public string clave { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public string email { get; set; }
        public string foto { get; set; }
        public bool activo { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Role Role { get; set; }
    }
}
